package engine.services.world.components;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class MusicComponentTest {

    private MusicComponent music;

    @BeforeEach
    void setUp() {
        // Use the single, correct constructor generated by Lombok
        music = new MusicComponent("test_music");
    }

    @Test
    void constructor_shouldSetHandleAndDefaults() {
        // Assert that the handle was set correctly by the constructor
        assertEquals("test_music", music.musicBufferHandle);

        // Assert that all other fields have their correct default values
        assertEquals(1.0f, music.baseVolume);
        assertEquals(1.0f, music.currentVolume);
        assertTrue(music.looping);
        assertTrue(music.autoPlay);
        assertEquals(2.0f, music.fadeDuration);
        assertFalse(music.fadingIn);
        assertFalse(music.fadingOut);
        assertEquals(0.0f, music.fadeTimer);
        assertFalse(music.isPlaying);
        assertFalse(music.isPaused);
    }

    @Test
    void startFadeIn_shouldSetFadingFlagsAndResetVolume() {
        music.currentVolume = 0.5f; // Simulate a different state
        music.startFadeIn();

        assertTrue(music.fadingIn);
        assertFalse(music.fadingOut);
        assertEquals(0.0f, music.fadeTimer);
        assertEquals(0.0f, music.currentVolume);
    }

    @Test
    void startFadeOut_shouldSetFadingFlags() {
        music.fadingIn = true; // Simulate a different state
        music.startFadeOut();

        assertFalse(music.fadingIn);
        assertTrue(music.fadingOut);
        assertEquals(0.0f, music.fadeTimer);
    }

    @Test
    void stopFade_shouldResetAllFadingAndSetVolumeToBase() {
        music.baseVolume = 0.8f;
        music.currentVolume = 0.2f;
        music.fadingIn = true;
        music.fadeTimer = 1.0f;

        music.stopFade();

        assertFalse(music.fadingIn);
        assertFalse(music.fadingOut);
        assertEquals(0.0f, music.fadeTimer);
        assertEquals(0.8f, music.currentVolume);
    }
}
